services:
  mongodb:
    image: mongo:latest
    container_name: study-data-eng-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
  postgres:
    image: postgres:latest
    container_name: study-data-eng-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: study-data-eng-postgress
    volumes:
      - ./data/postgres:/var/lib/postgresql
